# Taps

tap "hmarr/tap"
tap "pulumi/tap"
tap "railwaycat/emacsmacport"
tap "sst/tap"
tap "withgraphite/tap"

# Brews

brew "autoconf"
brew "automake"
brew "awscli"
brew "bacon"
brew "basedpyright"
brew "bat"
brew "bob"
brew "cargo-instruments"
brew "cfitsio"
brew "cocoapods"
brew "colima"
brew "coreutils"
brew "curl"
brew "delta"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "gemini-cli"
brew "gh"
brew "git-revise"
brew "git"
brew "gnu-sed"
brew "go"
brew "gopls"
brew "gpg"
brew "graphviz"
brew "helix"
brew "hmarr/tap/codeowners"
brew "htop"
brew "hyperfine"
brew "imagemagick"
brew "ispell"
brew "jless"
brew "jujutsu"
brew "lima"
brew "llm"
brew "make"
brew "mas"
brew "mergiraf"
brew "mise"
brew "node"
brew "pandoc"
brew "pkg-config"
brew "prr"
brew "pstree"
brew "pulumi/tap/pulumi"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rsync"
brew "sqlite3"
brew "sst/tap/opencode"
brew "stow"
brew "tmux"
brew "tokei"
brew "tree-sitter-cli"
brew "universal-ctags"
brew "uv"
brew "viddy"
brew "wakeonlan"
brew "watchexec"
brew "websocat"
brew "withgraphite/tap/graphite"
brew "xh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh"

# for localStack

brew "libvirt"
brew "snappy"

# Casks

cask "1password-cli"
cask "1password"
cask "betterdisplay"
cask "blender"
cask "brave-browser"
cask "claude-code"
cask "cursor"
cask "deskpad"
cask "docker-desktop"
cask "firefox@developer-edition"
cask "font-atkinson-hyperlegible-mono"
cask "font-commit-mono"
cask "ghostty"
cask "gimp"
cask "google-chrome"
cask "iina"
cask "inkscape"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keymapp"
cask "mitmproxy"
cask "notion"
cask "obs"
cask "obsidian"
cask "railwaycat/emacsmacport/emacs-mac"
cask "raycast"
cask "shotcut"
cask "slack"
cask "steam"
cask "tailscale-app"
cask "utm"
cask "visual-studio-code"
cask "vlc"
cask "wacom-tablet" if `hostname`.strip == "mm"
cask "wireshark-app"
cask "yaak"
cask "yubico-yubikey-manager" if `hostname`.strip == "mm"
cask "zed"
cask "zoom"

# for LocalStack

# Mac App Store apps
mas "1Password for Safari", id: 1569813296
mas "DaisyDisk", id: 411643860
