# Taps

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "messense/macos-cross-toolchains"
tap "mhanberg/zk"
tap "railwaycat/emacsmacport"
tap "aquasecurity/trivy"

# Formulae

brew "ansible"
brew "aquasecurity/trivy/trivy"
brew "awscli"
brew "bat"
brew "cfitsio"
brew "coreutils"
brew "curl"
brew "dark-mode"
brew "direnv"
brew "dos2unix"
brew "exa"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "gnupg"
brew "grep"
brew "htop"
brew "hub"
brew "jq"
brew "lab"
brew "mas"
brew "mhanberg/zk/zk"
brew "mosh", args: ["HEAD"]
brew "ncdu"
brew "neovim"
brew "noti"
brew "openssh"
brew "pandoc"
brew "pkg-config"
brew "pre-commit"
brew "pstree"
brew "railwaycat/emacsmacport/emacs-mac", args: ["with-modules"]
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rlwrap"
brew "sk"
brew "sqlc"
brew "ssh-copy-id"
brew "tmux"
brew "trash"
brew "tree"
brew "universal-ctags"
brew "wakeonlan"
brew "watch"
brew "watchexec"
brew "zsh"

# cross-compilation toolchains
brew "x86_64-unknown-linux-gnu"
brew "aarch64-unknown-linux-gnu"

# Casks

cask "alfred"
cask "barrier"
cask "dash"
cask "docker"
cask "drawio"
cask "element"
cask "firefox"
cask "gimp"
cask "google-chrome"
cask "hammerspoon"
cask "karabiner-elements"
cask "kitty"
cask "obsidian"
cask "skype"
cask "slack"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"

mas "Bitwarden", id: 1352778147
