" turn off unneeded gui crap
set go=

" if mac use the monaco font
if has("macunix")
    set gfn=Menlo:h12
else
    set gfn=Bitstream\ Vera\ Sans\ Mono\ 10
endif

" Disable cursor blinking in normal mode
set gcr=n:blinkon0

" Disable audible bell by enabling visual bell which is not implemented
set visualbell
