" turn off unneeded gui crap
set guioptions-=T
set guioptions-=m

" if mac use the monaco font
if has("macunix")
    set gfn=Monaco:h12
else
    set gfn=Bitstream\ Vera\ Sans\ Mono\ 10
endif

set sw=4
set transparency=5
