" turn off unneeded gui crap
set guioptions-=T
set guioptions-=m

" if mac use the monaco font
if has("macunix")
    set gfn=Monaco:h12
else
    set gfn=Bitstream\ Vera\ Sans\ Mono\ 10
endif

" Allow command T to build latex files
if has("gui_macvim")
  macmenu File.New\ Tab key=<nop>
  map <D-t> :make<CR>
endif

set sw=4
