" turn syntax highlighting on
if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
    syntax on
endif

" Load all of the plugins with vundle
if filereadable(expand("~/.vim/setup/bundles.vim"))
source ~/.vim/setup/bundles.vim
endif

" Remap the leader key to comma
let mapleader=','


" set up some nice tab defaults
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Set history settings
set history=700
set undolevels=700


" reload all file changes automatically
set autoread

" enable the semicolon to act like the colon key
" swap the keys to get the old semicolon functionality back
map ; :

" set incremental search
set incsearch

" set case options for searching
set ignorecase
set smartcase


" show command as it's typed
set showcmd


" nice file formatting
set autoindent

" always have status line on
set laststatus=2
set encoding=utf-8 " Necessary to show unicode glyphs


" make backspace behave nicely
set backspace=indent,eol,start

" Set mouse mode
set mouse=a

" Remap the move-window keys
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Remove the arrow key functionality
nnoremap <Up> :echo "no!"<cr>
nnoremap <Down> :echo "no!"<cr>
nnoremap <Left> :echo "no!"<cr>
nnoremap <Right> :echo "no!"<cr>
inoremap <Up> <esc>:echo "no!"<cr>
inoremap <Down> <esc>:echo "no!"<cr>
inoremap <Left> <esc>:echo "no!"<cr>
inoremap <Right> <esc>:echo "no!"<cr>


" disable f1 key
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" Set the tags directory
set tags=./tags;/

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

" Enable fast tty mode
set ttyfast

" Change the way tab autocompletion works
set wildmenu
set wildmode=list:longest,list:full

" Remap the Q key
map Q gq

" Make the Y key work
map Y y$

" Paste toggling - allow for pasting from other sources with correct
" formatting
set pastetoggle=<leader>p

" Disable escape keys which makes vim more responsive
" set noesckeys

" Hide buffers instead of closing them
set hidden

" Don't update the display while executing macros
set lazyredraw

" Set up statusline
set statusline=

" Buffer number and pipe character with spaces
set statusline+=%-3.3n\ 

" Filename relative to opening path
set statusline+=%f\ 

" Status markers
set statusline+=%h%m%r%q

" End of left section, start right section
set statusline+=%=

" File type
set statusline+=%y\ 

" Cursor position
set statusline+=%-14.(%l,%c%V%)\ 

" View position
set statusline+=%P

" Folding method
set foldmethod=marker

" Thesaurus
set thesaurus+=~/thesaurus/mthesaur.txt

" Change directory to that of the current file
" Taken from Dave Aitken http://www.github.com/actionshrimp
" Tweaked to run lcd instead of cd
map <leader>cd :lcd %:p:h<CR>:pwd<CR>

" Set colour scheme
set background=dark
colorscheme grb256

" Map control-s to update, rather than write
nmap <C-s> :update<CR>
imap <C-s> :update<CR>
vmap <C-s> :update<CR>

" Enable british spelling
set spelllang=en_gb

" Better formatting
set formatprg=par

" Swap the mark keys
nnoremap ' `
nnoremap ` '

" Add some lines around the cursor
set scrolloff=14

" Speed up ctrl-e/ctrl-y
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Configure 'Press enter to continue' messages
set shortmess=atI

" Decrease the leader key timeout for the comma key
set timeout timeoutlen=1000 ttimeoutlen=100



" Enable scrolljump
set scrolljump=5

" Disable conceal
set conceallevel=0

" Enable relativenumber
set relativenumber

" Enable number also to get the current line numbered, only in 7.4 and above
if version >= 704
    set number
endif

" settings from thoughtbot dotfiles repo
" Swap between two files
map <leader><leader> <C-^>

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Enable the ruler
set ruler

" Always show the tab line
set showtabline=2

" Set some ignore patterns
set wildignore+=*.aux,*.o,*.git

set switchbuf=useopen

" Jump back to last file position
au BufReadPost * 
    \ if line("'\"") > 1 && line("'\"") <= line("$") | 
    \ exe "normal! g`\"" | 
    \ endif


" Configure hlsearch 
set hlsearch
noremap <cr> :nohlsearch<cr>


" Now load the plugins settings
let s:plugin_settings = expand($HOME . '/.vim/setup/plugin_settings.vim')
if filereadable(s:plugin_settings)
    :exec ':so ' . s:plugin_settings
endif
