#! /bin/sh

~/.config/polybar/polybar.sh

sxhkd &

bspc monitor DVI-D-0 -d 6 7 8 9
bspc monitor DP-2 -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         20

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colours
bspc config normal_border_color		"#2E3440"
bspc config active_border_color		"#D8DEE9"
bspc config focused_border_color	"#D8DEE9"
bspc config presel_feedback_color	"#2E3440"

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Compositing
if [ -x "$(command -v picom)" ]; then
    killall picom >/dev/null 2>&1 || true
    picom -b --dbus
fi

nm-applet &
