# vim: ft=tmux
# rosé pine
fg_colour="#9ccfd8"
bg_colour="default"

status_format_colour="#908caa"

set -g message-style "fg=$fg_colour,bg=$bg_colour"
set -g message-command-style "fg=$fg_colour,bg=$bg_colour"

set -g pane-border-style "fg=#403d52"
set -g pane-active-border-style "fg=$fg_colour"

set -g status-style "fg=$fg_colour,bg=$bg_colour"
set -g status-bg default

set -g status-left "#[fg=$fg_colour,bold]#S ▶  "
set -g status-right "  #[fg=$fg_colour,bold]◀ #h"

setw -g window-status-activity-style "underscore,fg=#e0def4,bg=$bg_colour"
setw -g window-status-style "fg=$status_format_colour,bg=$bg_colour,nobold"
setw -g window-status-current-style "fg=#c4a7e7,bg=$bg_colour,nobold"
setw -g window-status-format "#{?window_zoomed_flag,#[fg=#f6c177],#[fg=$status_format_colour]} #I:#{?window_name,#{window_name},#{pane_current_command}} #[fg=$status_format_colour]"
setw -g window-status-current-format "#{?window_zoomed_flag,#[fg=#f6c177],#[fg=#c4a7e7]} #I:#{?window_name,#{window_name},#{pane_current_command}} #[fg=#c4a7e7]"
