#!/usr/bin/env bash

# Run atom if it exists on the system,
# otherwise run vim

set -e

# Function to determine if the system has the command specified.
#
# Taken from https://stackoverflow.com/a/677212/56711
has_executable() {
    if [[ $# != 1 ]]; then
        echo "has_executable requires one argument" >&2
        return 1
    fi

    command -v $1 >/dev/null 2>/dev/null
}

main() {
    if has_executable atom; then
        atom --wait --add "$@"
    else
        =vim "$@"
    fi
}

main $@
