#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import os
import subprocess as sp

def main(args):
    full_path = os.path.realpath(args.path)
    cmd = ['conda', 'create', '-p', full_path,
            '--yes', '--quiet']
    cmd.extend(args.package)
    sp.check_call(map(str, cmd))


if __name__ == '__main__':
    DEFAULT_PATH = os.path.realpath(
        os.path.join(
            os.getcwd(), 'venv'
        )
    )
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-p', '--path', required=False,
                        default=DEFAULT_PATH,
                        help='Path to create environment at')
    parser.add_argument('package', nargs='*')
    main(parser.parse_args())
