#!/usr/bin/env python3

import subprocess as sp

cmd = ["docker", "ps", "-a", "--format", "{{.ID}}|{{.Labels}}"]
res = sp.check_output(cmd).decode()

clear_args = []

for line in res.splitlines():
    id, rest = line.split("|", maxsplit=2)
    labels = [kv.split("=", maxsplit=2) for kv in rest.split(",")]
    skip_container = False
    for every in labels:
        if len(every) != 2:
            continue

        k, v = every[:2]
        if k.strip() == "clear" and v.strip() == "false":
            skip_container = True
            break
    if skip_container:
        continue

    clear_args.append(id)

if clear_args:
    cmd = ["docker", "rm", "-f"] + clear_args
    sp.check_call(cmd)
