#!/usr/bin/env python3

import argparse
import os
import subprocess as sp

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("pr_id")
    parser.add_argument("-r", "--remote", help="Remote to fetch from", default="origin")
    parser.add_argument("-n", "--no-fetch", action="store_true", default=False, help="Do not fetch")
    args, extra = parser.parse_known_args()

    # fetch
    if not args.no_fetch:
        cmd = ["git", "fetch", args.remote, f"refs/pull/{args.pr_id}/head"]
        sp.check_call(cmd)
    # show log
    cmd = ["git", "log", "FETCH_HEAD"] + extra
    os.execvp(cmd[0], cmd)
