#!/usr/bin/env bash

set -e

run_sed_command() {
    if command -v gsed 2>&1 >/dev/null; then
        gsed -E 's/\s+/+/g'
    else
        sed -E $'s/ +/+/g'
    fi
}

main() {
    local readonly search_command="$(echo $@ | run_sed_command)"
    w3m "https://www.google.com/search?hl=en&q=${search_command}"
}

main "$@"
