#!/usr/bin/env bash

set -euo pipefail

git branch --no-column --sort -committerdate --format "%(refname:short) %(color:blue)%(authordate:relative) %(authorname)" | fzf --ansi --preview 'echo {} | cut -f 1 -d " " | xargs git show' --select-1 --exit-0 | cut -f 1 -d ' ' | xargs git checkout
