#!/usr/bin/env bash

set -euo pipefail

function print_all_panes() {
    for pane_id in $(tmux list-panes -F '#{pane_id}'); do
        tmux capture-pane -p -J -S 0 -E - -t "$pane_id" | tr ' ' '\n' | sort -u | rg '[a-zA-Z0-9]+'
    done
}

function main() {
    local value=$(print_all_panes | fzf-tmux --height 20 --layout reverse --no-sort)
    echo -n $value
}


main "$@"

