#!/usr/bin/env bash

set -euo pipefail

function print_all_panes() {
    if [[ -n "${ZMX_SESSION:-}" ]]; then
        zmx history "$ZMX_SESSION" | tr ' ' '\n' | sort -u | rg '[a-zA-Z0-9]+'
    else
        history 0 | tr ' ' '\n' | sort -u | rg '[a-zA-Z0-9]+'
    fi
}

function main() {
    local value=$(print_all_panes | fzf --height 20 --layout reverse --no-sort)
    echo -n $value
}


main "$@"
