#!/usr/bin/env python
#
# set -euo pipefail
#
# function usage() {
#     echo "Usage: $0 <pr-def>" >&2
#     echo >&2
#     echo "  Example: $0 localstack/localstack/12345" >&2
#     exit 1
# }
#
# if [[ -z ${1:-} || $1 == "-h" || $1 == "--help" ]]; then
#     usage
# fi
#
# pr_ref="$1"
#
# if ! $(echo $pr_ref | rg -q '^(\w+/){2}\d+$'); then
#     echo "Invalid PR ref: '$pr_ref'" >&2
#     echo >&2
#     echo "  Example: $0 localstack/localstack/12345" >&2
#     exit 1
# fi
#
# system_prompt="You are a senior software engineer. Focus on issues that you find. Do not summarise the PR."
#
# llm --usage --system "$system_prompt" -f "pr:$pr_ref" 'review this code'


import argparse
import re
import sys
import os

import subprocess as sp


def error_log(message: str):
    print(message, file=sys.stderr)
    sys.exit(1)


PR_REF_RE = re.compile(r"^(?P<owner>[a-z-]+)/(?P<repo>[a-z-]+)/\d+")

parser = argparse.ArgumentParser()
parser.add_argument("pr")
parser.add_argument("-m", "--model", help="Model to use")
args = parser.parse_args()

if match := PR_REF_RE.match(args.pr):
    if match.group("owner") == "localstack" and match.group("repo") == "localstack-pro":
        # set the token so we can access private repos
        os.environ["GITHUB_TOKEN"] = sp.check_output(["gh", "auth", "token"]).decode().strip()
else:
    error_log(f"Invalid PR ref '{args.pr}'. Example: localstack/localstack/12345")

system_prompt = "You are a senior software engineer. Focus on issues that you find. Do not summarise the PR."

args = [
    "llm",
    "--usage",
    "--system",
    system_prompt,
    "--fragment",
    f"pr:{args.pr}",
    "review this code",
]
os.execvp("llm", args)
