#!/usr/bin/env bash

set -euo pipefail

function usage() {
    echo "Usage: $0 <pr-def>" >&2
    echo >&2
    echo "  Example: $0 localstack/localstack/12345" >&2
    exit 1
}

if [[ -z ${1:-} || $1 == "-h" || $1 == "--help" ]]; then
    usage
fi

pr_ref="$1"

if ! $(echo $pr_ref | rg -q '^(\w+/){2}\d+$'); then
    echo "Invalid PR ref: '$pr_ref'" >&2
    echo >&2
    echo "  Example: $0 localstack/localstack/12345" >&2
    exit 1
fi

system_prompt="You are a senior software engineer. Focus on issues that you find. Do not summarise the PR."

llm --usage --system "$system_prompt" -f "pr:$pr_ref" 'review this code'
