#!/usr/bin/env python3

import argparse
import os
from pathlib import Path

NOTES_PATH = Path.home() / "notes.md"

description = """
Open my singular notes file
"""

parser = argparse.ArgumentParser(
    usage="Open notes file",
    description=description,
)
parser.add_argument("-T", "--no-split", action="store_true", default=False, help="Open the file in this terminal surface")
args = parser.parse_args()

cmd = ["nvim", "-c", "normal G", str(NOTES_PATH)]
os.execvp(cmd[0], cmd)
