#!/usr/bin/env bash
#
# Attach or create a zmx session named the same as current directory.

set -euo pipefail

path_name="$(zmx-session-name "$(basename "$(dirname "$PWD")")" "$(basename "$PWD")")"
session_name="$(zmx-session-name "${1:-$path_name}")"

exec zmx attach "$session_name"
