#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import division, print_function, absolute_import
import subprocess as sp

def check_output(command):
    p = sp.Popen(command, stdout=sp.PIPE)
    stdout, stderr = p.communicate()
    if p.returncode != 0:
        raise RuntimeError("Command %s failed with return code %d" % (command, p.returncode))
    return stdout


def main():
    print(check_output(['zmx', 'list']).decode('utf-8'), end='')


if __name__ == '__main__':
    main()
