#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import division, print_function, absolute_import
import datetime
import subprocess as sp

def build_job_mapping(lines):
    for line in lines:
        line = line.strip()
        if line:
            time_str = line.split('(created')[-1].split(')')[0].strip()
            time = datetime.datetime.strptime(time_str,
                    '%a %b %d %H:%M:%S %Y')
            title = line.split(':')[0].strip()
            yield {
                    'time': time,
                    'title': title,
                    'text': line,
                    }

def check_output(command):
    p = sp.Popen(command, stdout=sp.PIPE)
    stdout, stderr = p.communicate()
    if p.returncode != 0:
        raise RuntimeError("Command %s failed with return code %d" % (command, p.returncode))
    return stdout


def main():
    command = ['tmux', 'ls']
    lines = check_output(command).decode('utf-8').split('\n')
    job_mapping = build_job_mapping(lines)
    for line in sorted(job_mapping, key=lambda row: row['time']):
        print(line['text'])


if __name__ == '__main__':
    main()
