#!/usr/bin/env bash

tmup () {
    echo -n "Updating to latest tmux environment...";
    IFS='\n';
    for line in $(tmux showenv -t "$(tmux display -p '#S')"); do
        if [[ $line == -* ]]; then
            unset $(echo $line | cut -c2-);
        else
            export $line;
        fi;
    done;
    unset IFS;
    echo "Done"
}

tmup
