#!/usr/bin/env python3

import subprocess as sp
from pathlib import Path
from datetime import datetime, timezone, timedelta
import logging
import argparse

logging.basicConfig(
    level=logging.WARNING, format="%(asctime)s|%(levelname)s: %(message)s"
)
logger = logging.getLogger("tmux-prune")


def kill_session(name):
    sp.check_call(["tmux", "kill-session", "-t", name])


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", "--force", action="store_true", default=False)
    parser.add_argument("-C", "--created", action="store_true", default=False,
                        help="Use session created at rather than last activity")
    parser.add_argument(
        "-c",
        "--cutoff",
        required=False,
        help="Cutoff time in days",
        type=int,
        default=5,
    )
    parser.add_argument("-v", "--verbose", action="count", default=0)
    args = parser.parse_args()

    if args.verbose == 1:
        logger.setLevel(logging.INFO)
    elif args.verbose > 1:
        logger.setLevel(logging.DEBUG)

    now = datetime.now(tz=timezone.utc)
    cutoff = now - timedelta(days=args.cutoff)

    prune_dir = Path.home() / ".tmux" / "prunes"
    prune_dir.mkdir(exist_ok=True, parents=True)
    logger.info(f"using prune directory {prune_dir}")

    logger.info(f"now:\t{now}")
    logger.info(f"cutoff:\t{cutoff}")

    to_prune = []

    timestamp_key = "session_created" if args.created else "session_activity"
    cmd = ["tmux", "ls", "-F", "#S #{%s}" % timestamp_key]
    output = (
        sp.check_output(cmd)
        .decode()
        .split("\n")
    )
    for line in output:
        line = line.strip()
        if not line:
            continue

        parts = line.split()
        if len(parts) != 2:
            logger.warning(f"invalid output")
            continue
        name, activity = parts
        activity = datetime.fromtimestamp(int(activity))
        # XXX: this may be different depending on what timezone the user is,
        # however it is unlikely to be out by near the cutoff period (default:
        # 1 week)
        if activity < cutoff.replace(tzinfo=None):
            logger.info(
                f"session {name} last activity {activity:%Y-%m-%d %H:%M:%S} pruning"
            )
            to_prune.append(name)
        else:
            logger.debug(
                f"session {name} last activity {activity:%Y-%m-%d %H:%M:%S} not pruning"
            )

    if len(to_prune) == 0:
        logger.info("no sessions to prune found")
        exit(0)

    if not args.force:
        logger.warning("-f/--force not supplied; not pruning")
        exit(0)

    prune_fname = prune_dir / f"{now}.txt"
    assert not prune_fname.is_file()
    with prune_fname.open("w") as outfile:
        for prune in to_prune:
            kill_session(prune)
            print(prune, file=outfile)
