#!/usr/bin/env bash

# Creates a second session that can separately control an existing session.

set -eou pipefail


main() {
    readonly sessionname="$(tmux ls -F '#S' | fzf)"
    readonly sessionid="${sessionname}-$(uuidgen)"

    tmux new-session -s $sessionid -t ${sessionname} || true
    tmux kill-session -t $sessionid
}

main "$@"
