#!/usr/bin/env bash

set -eu

verify_args() {
    if [[ ! "$#" == 1 ]]; then
        echo "Program usage: $0 <session_name>" >&2
        exit 1
    fi

    session_name="$1"
}

main() {
    verify_args "$@"

    exec zmx attach "$(zmx-session-name "${session_name}")"
}

main "$@"
