#!/usr/bin/env bash

set -euo pipefail

log() {
    echo "$@" >&2
}

die() {
    log "$@"
    exit 1
}

if [ $# -ne 2 ]; then
    die "Usage: wait-for-output <command> <output>"
fi

CMD="$1"
OUTPUT="$2"

while true; do
    stdout="$($CMD)"

    echo -n $stdout | grep -q $OUTPUT && {
        log "Specified output found; exiting"
        break
    }

    sleep 10
done
