#!/usr/bin/env python3

import argparse
import subprocess
import socket
import sys


def wake():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-b", "--broadcast", help="Broadcast IP address", default="192.168.1.255"
    )
    parser.add_argument("-m", "--mac", help="MAC Address", default="40:B0:76:DE:79:B3")
    args = parser.parse_args()

    subprocess.run(
        ["wakeonlan", "-i", args.broadcast, "-p", "7", args.mac],
        stdout=subprocess.DEVNULL,
    )

    ip_address = socket.gethostbyname("astoria")
    subprocess.run(["ping", "-o", ip_address], stdout=subprocess.DEVNULL)


if __name__ == "__main__":
    try:
        wake()
    except KeyboardInterrupt:
        sys.exit(130)
