
# Handle nice suspend
# xss-lock -- i3lock --color 333333 --show-failed-attempts &

# Set the screen configuration
# xrandr --output DP-2 --primary --right-of DVI-D-0

# Start the notification handler
# /usr/bin/dunst &

# Set the keyboard map
# xmodmap ~/.Xmodmap

# Configure keyboard map
# bash ~/.bin/set-keyboard

# Start XFCE
exec mate-session
