userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

if [ -x /etc/X11/xinit/xinitrc.d/50-systemd-user.sh ]; then
   . /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
fi

# Configure keyboard map
bash ~/.bin/set-keyboard

# Start MATE
exec mate-session
