# Set the keyboard map to UK layout
setxkbmap gb

# Handle nice suspend
xss-lock -- i3lock --color 333333 --show-failed-attempts &

# Set the screen configuration
# xrandr --output DP-2 --primary --right-of DVI-D-0

# Start the notification handler
# /usr/bin/dunst &

# Set the keyboard map
xmodmap ~/.Xmodmap

# Configure xcape
setxkbmap -option 'caps:ctrl_modifier'
xcape -t 100 -e 'Caps_Lock=Escape;Control_L=Escape;Control_R=Escape'

# Start KDE
export DESKTOP_SESSION=plasma
exec startplasma-x11
