#!/usr/bin/env bash

set -ex

# Copy the base config
cp ${HOME}/.i3/config.d/base ~/.i3/config

# Copy any host-specific customisations
cat "${HOME}/.i3/config.d/$(hostname -s)" >> ~/.i3/config

# Finally copy any non-tracked files
test -f ${HOME}/.i3/config.d/config.local && cat ${HOME}/.i3/config.d/config.local >> ${HOME}/.i3/config || true
