# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "wl"];
  boot.extraModulePackages = [config.boot.kernelPackages.broadcom_sta];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9839d4de-00b0-4010-acb4-c506e97e9403";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/DC84-18FB";
    fsType = "vfat";
  };
  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/893193eb-7680-48e9-a459-7af16e918548";
    fsType = "ext4";
    options = ["rw" "user" "exec" "noatime"];
  };

  swapDevices = [{device = "/dev/disk/by-uuid/780f83aa-7f7c-4f77-bc7c-b0c173fc57d1";}];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    opengl = {
      enable = true;
      driSupport32Bit = true;
    };
    bluetooth.enable = true;
    nvidia = {
      modesetting.enable = true;
      package = config.boot.kernelPackages.nvidiaPackages.beta;
      powerManagement.enable = true;
    };
  };

  environment.sessionVariables = {
    LIBVA_DRIVER_NAME = "nvidia";
  };

  services.xserver.xrandrHeads = [
    {
      output = "DP-0";
      monitorConfig = ''Option "Rotate" "left"'';
    }
    {
      output = "DP-2";
      primary = true;
    }
  ];
}
