require('disables')
require('settings')
require('plugins')
require('mappings')
require('customlspconfig')
require('treesitterconfig')
require('completion')

-- plugins
require('fzf')
require('vim-test')
require('vtr')
require('fugitive')
require('treesitter-unit-config')
require('telescopeconfig')
