local set = vim.opt

set.autowrite = true
set.backspace = {"indent", "eol", "start"}
set.backup = false
set.backupcopy = "auto"
set.backupdir = {"~/.vim/backup"}
set.breakindent = true
set.complete = {".", "w", "b", "u", "t", "i"}
set.completeopt = {"menuone", "preview"}
set.conceallevel = 0
set.cursorline = false
set.expandtab = true
set.formatoptions = "jtcroql"
set.gdefault = true
set.grepprg = "rg --vimgrep"
set.hidden = true
set.history = 50
set.hlsearch = false
set.ignorecase = true
set.inccommand = "split"
set.incsearch = true
set.lazyredraw = false
set.laststatus = 2
set.linebreak = true
set.list = false
set.modeline = true
set.mouse = "a"
set.number = true
set.relativenumber = true
set.ruler = false
set.scrolloff = 8
set.shiftround = true
set.shiftwidth = 4
set.shortmess = "tToOFIWa"
set.showcmd = true
set.signcolumn = "yes"
set.smartcase = true
set.smartindent = true
set.splitbelow = true
set.splitright = true
set.swapfile = true
set.switchbuf = {"useopen", "uselast"}
set.synmaxcol = 1024
set.tabstop = 4
set.tags = {".git/tags"}
set.termguicolors = true
set.textwidth = 0
set.timeoutlen = 500
set.ttimeoutlen = 10
set.undofile = true
set.updatetime = 4000
set.wildmode = {"list:longest", "list:full"}
set.winwidth = 80
set.wrap = false
set.writebackup = false
set.guicursor = ""
