theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#575279"
      secondary: "#286983"
      inverted: "#faf4ed"
      faint: "#797593"
      warning: "#ea9d34"
      success: "#56949f"
      error: "#b4637a"
    background:
      selected: "#f2e9e1"
    border:
      primary: "#286983"
      secondary: "#dfdad9"
      faint: "#f2e9e1"

