theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "#e0def4"
      secondary: "#9ccfd8"
      inverted: "#191724"
      faint: "#908caa"
      warning: "#f6c177"
      success: "#9ccfd8"
      error: "#eb6f92"
    background:
      selected: "#26233a"
    border:
      primary: "#9ccfd8"
      secondary: "#403d52"
      faint: "#26233a"

