prSections:
- title: "LS: Review requested"
  filters: "is:pr is:open review-requested:@me org:localstack draft:false"
- title: "LS: My Pull Requests"
  filters: "is:pr is:open author:@me org:localstack"
  layout:
    author:
      hidden: true
- title: "LS: Assigned"
  filters: "is:pr is:open assignee:@me org:localstack"
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: "LS: Involved"
  filters: "is:issue is:open involves:@me org:localstack"
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
- title: "LS: issues"
  filters: is:open org:localstack
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
  - key: W
    command: "gh pr view -w {{.PrNumber}} -R {{.RepoName}}"
  branches: []
repoPaths:
  localstack/*: "~/work/localstack/*"
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: "delta"
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
