---
apt_keys:
  - url: https://mise.jdx.dev/gpg-key.pub
    keyring: /etc/apt/keyrings/mise.gpg

apt_repositories:
  - repo: "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.pub arch=amd64] https://mise.jdx.dev/deb stable main"
    filename: mise
  - repo: "ppa:fish-shell/release-4"
    filename: fish-shell-release-4

packages:

  - 1password
  - 1password-cli
  - bridge-utils          # kvm
  - bubblewrap            # for claude sandboxing
  - build-essential
  - cmake
  - cpu-checker           # kvm
  - curl
  - emacs
  - eza
  - fd-find
  - ffmpeg
  - fish
  - fonts-jetbrains-mono
  - git-delta
  - gnome-tweaks
  - htop
  - libcfitsio-dev
  - liblua5.4-dev
  - libnss3-tools         # mkcert
  - libssl-dev
  - libvirt-clients       # kvm
  - libvirt-daemon        # kvm
  - lua5.4
  - mise
  - mosh
  - podman
  - python3-psutil           # dconf module
  - qemu-system
  - ripgrep
  - socat                 # for claude sandboxing
  - sqlite3
  - stow
  - tmux
  - unattended-upgrades
  - virt-manager
  - wmctrl
  - x11vnc
  - zsh

snaps:

  - slack
  - steam

classic_snaps:

  - pycharm
