---
- name: Ensure managed user groups exist
  become: true
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ dotfiles_user_groups }}"

- name: Configure managed user account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_target_user }}"
    groups: "{{ dotfiles_user_groups }}"
    append: true
    shell: "{{ dotfiles_user_shell }}"

- name: Create ~/.local/bin
  ansible.builtin.file:
    dest: "{{ ansible_target_home }}/.local/bin"
    state: directory
    owner: "{{ ansible_target_user }}"

- name: Create fd symlink
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: "{{ ansible_target_home }}/.local/bin/fd"
    state: link
