skip_global_compinit=1

export BUILD_PREFIX="${HOME}/.local"
export PATH=${BUILD_PREFIX}/bin:${HOME}/.bin:${HOME}/.bin/ngts:${HOME}/.cabal/bin:/usr/local/bin:${PATH}:${HOME}/.cargo/bin:${HOME}/bin
export EDITOR=emacs
export VISUAL=${EDITOR}

# Set up rust
export PATH=${PATH}:${HOME}/.cargo/bin

# Source the custom zshenv.local file in the system
if [[ -f ${HOME}/.zshenv.local ]]; then
    source ${HOME}/.zshenv.local
fi
