PROFILE_STARTUP=false
if [[ "$PROFILE_STARTUP" == true ]]; then
    zmodload zsh/zprof
fi

export PATH=${HOME}/.bin:${HOME}/.poetry/bin:${HOME}/.cabal/bin:/usr/local/bin:${PATH}:${HOME}/bin
fpath=($HOME/.zsh/func $HOME/.zsh/completion $fpath)
typeset -U fpath

# Report the time taken for any long running command
REPORTTIME=10

# Disable Ctrl-s freezing the terminal
stty stop undef

autoload -U compinit
compinit -i

autoload add-zsh-hook

# Disable non-standard implicit tee/cat behaviour
unsetopt multios

autoload -U bashcompinit

# Emacs keybindings
bindkey -e
bindkey "^R" history-incremental-search-backward
bindkey -v '^?' backward-delete-char

# Set up editor in command line
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

autoload -U colors
colors

setopt interactivecomments
setopt rmstarsilent
setopt prompt_subst
setopt inc_append_history
setopt share_history
unsetopt auto_pushd

# Only unique history entries in the reverse history search HIST_FIND_NO_DUPS=1
setopt hist_ignore_all_dups
setopt hist_ignore_dups


# Ignore duplicate history entries
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes

# Speed up completion
zstyle ':completion:*' accept-exact '*(N)'

# Use a cache for completion
zstyle ':completion:*' use-cache on


HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=$HISTSIZE


export GOPATH=${HOME}/dev/gocode
export PATH=${PATH}:${GOPATH}/bin

export EDITOR=vim_or_nvim
export VISUAL=${EDITOR}
export BIBINPUTS=${HOME}/work/central-bibliography:${BIBINPUTS}
export LESS='-FXR'

# Set up fzf
export FZF_DEFAULT_OPTS="--color dark --tac --ansi --no-mouse --tabstop 4 --inline-info --tiebreak=begin,length"
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow -g "!{.git,venv,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"

# Add persistent history to elixir shell
export ERL_AFLAGS="-kernel shell_history enabled"

# Taken from grb's zshrc

# By default, zsh considers many characters part of a word (e.g., _ and -).
# Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'


export BUILD_PREFIX="${HOME}/.local"
export MANPATH=${BUILD_PREFIX}/share/man:${MANPATH}
export PATH=${BUILD_PREFIX}/bin:${PATH}:${HOME}/.nimble/bin


export WASP="${work}/WASP"
export NGTS="${work}/NGTS"
export ZLP="${NGTS}/pipeline/ZLP"
export LOGDIR="${HOME}/var/log"
export TREE_CHARSET=ascii               # For rendering with the `tree` command

export EMAIL=s.r.walker101@googlemail.com

# Disable cowsay for ansible
export ANSIBLE_NOCOWS=1

# source external zsh setup files
for file in ~/.zsh/setup/*.zsh; do
    source $file
done

# Set up rustup
export CARGO_HOME=${HOME}/.cargo
export PATH=${CARGO_HOME}/bin:${PATH}
if has_executable "rustc"; then
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi
export RUST_NEW_ERROR_FORMAT=true
export RUST_BACKTRACE=0

# Set up misc extra commands
export PYENV_VIRTUALENV_DISABLE_PROMPT=1

# Source the custom zshrc.local file in the system
if [[ -f ${HOME}/.zshrc.local ]]; then
    source ${HOME}/.zshrc.local
fi

if [[ "$PROFILE_STARTUP" == true ]]; then
    unsetopt xtrace
    exec 2>&3 3>&-
fi

export PATH=${PATH:+:${PATH}}:/usr/local/cuda/bin
export LD_LIBRARY_PATH=${BUILD_PREFIX}/lib:${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
export PKG_CONFIG_PATH=${BUILD_PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}

# Set up GPG
export GPG_TTY="$(tty)"

# Configure safely including directories on the path, if the path .git/safe exists
# https://thoughtbot.com/blog/git-safe

export PATH="${PATH}:.git/safe/../../bin"

alias g=git

# Finally source the theme
if has_executable starship; then
    export STARSHIP_CONFIG=~/.config/starship/starship.toml
    eval "$(starship init zsh)"
else
    muted_print "Cannot find starship"
    source ${HOME}/.zsh/srwalker101.zsh-theme
fi

if [[ "$PROFILE_STARTUP" == true ]]; then
    zprof
fi
