#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
ctags --tag-relative -Rf.git/tags.$$ --exclude=tmp --languages=-javascript
mv $dir/tags.$$ $dir/tags
