#!/usr/bin/env python

import os
import shlex
import subprocess as sp
import sys


def exit_if_failure(fn):
    def inner(*args, **kwargs):
        output = fn(*args, **kwargs)
        try:
            output.check_returncode()
        except sp.CalledProcessError:
            print("❌ precommit hook failed ❌", file=sys.stderr)
            print(output.stderr.decode(), file=sys.stderr)
            sys.exit(1)

    return inner


@exit_if_failure
def vet_rust_project():
    return run("cargo fmt --quiet -- --check")


@exit_if_failure
def vet_python_project(path):
    return run(f"black --check {path} tests")


def run(s):
    return sp.run(shlex.split(s), stdout=sp.PIPE, stderr=sp.PIPE)


if __name__ == "__main__":
    if os.path.isfile("Cargo.toml"):
        vet_rust_project()
    elif os.path.isdir("src"):
        vet_python_project("src")
    elif os.path.isdir("lambda_function"):
        vet_python_project("lambda_function")

