#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -e

echo "Running tests before push"

# customise the variable below
PYTHON_PROJECTDIRS="setup.py tests"

test-python() {
    test -z "${PYTHON_PROJECTDIRS:-}" && {
        echo "No black paths set" >&2
        exit 1
    }

    black --check --target-version py38 $PROJECTDIRS --quiet || {
        echo "Black check failed! 💥💔💥" >&2
        exit 1
    }
    flake8
    pytest --quiet --disable-warnings
}

test-rust() {
    cargo test
}

# Do not allow pushes without validating what pre-push commands are wanted
echo "*** NO TESTS SET UP YET, BLOCKING PUSH ***"
exit 1
