#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -e

echo "Running tests before push"

echo "*** NO TESTS SET UP YET ***"

# XXX Running tox?
# ./venv/bin/tox

# XXX Running pytest?
# ./venv/bin/pytest

# XXX Running cargo?
# cargo test
