#!/usr/bin/env bash
#MISE description="Install homebrew packages from bundle file"

set -eou pipefail

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_BUNDLE_CLEANUP_NO_MAS=1

brew bundle --jobs auto --no-upgrade --force
brew bundle cleanup --all --force
