#!/usr/bin/env bash
#MISE description="Install local cargo projects from ~/dev"

set -euo pipefail

PROJECTS=(
    https://github.com/simonrw/cftail
    https://github.com/simonrw/testsearch
    https://github.com/simonrw/lbtree
)

for project in "${PROJECTS[@]}"; do
    cargo install --git $project --locked
done
