#!/usr/bin/env python
# MISE description="Install agents skills"

from pathlib import Path
import subprocess as sp
import sys

type Repo = str
type Name = str

SKILLS: dict[Repo, list[Name]] = {
    "mattpocock/skills": [],
    "simonrw/skills": [],
    "DietrichGebert/ponytail": [],
}

# Install private skills which may fail if we don't have access
PRIVATE_SKILLS: dict[Repo, list[Name]] = {
    "simonrw/skills-private": [],
}

AGENTS: list[str] = ["codex", "claude-code", "pi"]

UNINSTALL_LIST: list[str] = ["caveman"]


def install_skill(repo: Repo, names: list[Name]):
    command = ["npx", "skills@latest", "add", "--global", repo] + ["--agent"] + AGENTS
    if names:
        command = command + ["--skill"] + names

    sp.check_call(command)


# first clear the directory
sp.check_call(["npx", "skills@latest", "remove", "--global", "--all", "--yes"])

for repo, names in SKILLS.items():
    install_skill(repo, names)

for repo, names in PRIVATE_SKILLS.items():
    try:
        install_skill(repo, names)
    except Exception as e:
        print(f"Error installing private skills from {repo}: {e}", file=sys.stderr)
        continue

# then install openspec globally
sp.check_call(
    ["mise", "exec", "--", "openspec", "init", "--tools", "codex"], cwd=Path.home()
)

# potentially remove skills
if not UNINSTALL_LIST:
    exit()

command = ["npx", "skills@latest", "rm", "--global", "--yes"] + UNINSTALL_LIST
sp.check_call(command)
