#!/usr/bin/env python
# MISE description="Install agents skills"

import subprocess as sp

type Repo = str
type Name = str

SKILLS: dict[Repo, list[Name]] = {
    "mattpocock/skills": [],
    "simonrw/skills": [],
}

AGENTS: list[str] = ["codex", "claude-code", "pi"]

UNINSTALL_LIST: list[str] = ["caveman"]

# first clear the directory
sp.check_call(["npx", "skills@latest", "remove", "--global", "--all", "--yes"])

for repo, names in SKILLS.items():
    # add skills
    command = (
        ["npx", "skills@latest", "add", "--global", repo]
        + ["--agent"]
        + AGENTS
    )
    if names:
        command = command + ["--skill"] + names

    sp.check_call(command)

# potentially remove skills
if not UNINSTALL_LIST:
    exit()

command = ["npx", "skills@latest", "rm", "--global", "--yes"] + UNINSTALL_LIST
sp.check_call(command)
