#!/usr/bin/env python
# MISE description="Install agents skills"

import subprocess as sp
import sys

type Repo = str
type Name = str

SKILLS: dict[Repo, list[Name]] = {
    "mattpocock/skills": [
        "diagnosing-bugs",
        "grill-me",
        "grilling",
        "wait-what",
        "wait-what",
        "writing-for-agents",
        "improve-writing",
    ],
    "simonrw/skills": [],
    "painhardcore/pstack": [],
}

# Install private skills which may fail if we don't have access
PRIVATE_SKILLS: dict[Repo, list[Name]] = {
    "simonrw/skills-private": [],
}

AGENTS: list[str] = ["codex", "pi"]

UNINSTALL_LIST: list[str] = ["caveman"]


def install_skill(repo: Repo, names: list[Name]):
    command = ["npx", "skills@latest", "add", "--global", repo] + ["--agent"] + AGENTS
    if names:
        command = command + ["--skill"] + names

    sp.check_call(command)


# first clear the directory
sp.check_call(["npx", "skills@latest", "remove", "--global", "--all", "--yes"])

for repo, names in SKILLS.items():
    install_skill(repo, names)

for repo, names in PRIVATE_SKILLS.items():
    try:
        install_skill(repo, names)
    except Exception as e:
        print(f"Error installing private skills from {repo}: {e}", file=sys.stderr)
        continue

# potentially remove skills
if not UNINSTALL_LIST:
    sys.exit()

command = ["npx", "skills@latest", "rm", "--global", "--yes"] + UNINSTALL_LIST
sp.check_call(command)
