" turn off unneeded gui crap
set go=

" Use console popups
set go+=c

" if mac use the Hack font
if has("macunix")
    set gfn=Hack:h14
else
    set gfn=Bitstream\ Vera\ Sans\ Mono\ 10
endif

" Disable cursor blinking in normal mode
set gcr=n:blinkon0

" Disable audible bell by enabling visual bell which is not implemented
set visualbell

" Set width
set columns=100
