let g:mapleader = ","
let g:maplocalleader = '\\'

call plug#begin('~/.vim/bundle')

if !has('nvim')
    Plug 'tpope/vim-sensible'
endif

Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install --no-update-rc --no-completion --key-bindings' }
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-dispatch'
Plug 'christoomey/vim-tmux-runner'
Plug 'christoomey/vim-conflicted'
Plug 'vim-test/vim-test'
Plug 'cespare/vim-toml', { 'for': 'toml' }
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
Plug 'junegunn/goyo.vim'
Plug 'fatih/vim-go', { 'for': 'go' }
Plug 'hashivim/vim-terraform'
Plug 'uarun/vim-protobuf'
Plug 'junegunn/vim-easy-align'
Plug 'jvirtanen/vim-hcl'
Plug 'martinda/Jenkinsfile-vim-syntax'
Plug 'chr4/nginx.vim'
Plug 'airblade/vim-gitgutter'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-notes'
Plug 'vmchale/dhall-vim', { 'for': 'dhall' }
Plug 'ElmCast/elm-vim', { 'for': 'elm' }
Plug 'dracula/vim'
Plug 'morhetz/gruvbox'
Plug 'neoclide/coc.nvim', { 'branch': 'release' }
let g:airline_theme = "dracula"
Plug 'vim-airline/vim-airline'
Plug 'chriskempson/base16-vim'

if has('nvim-0.5')
    augroup LuaHighlight
        autocmd!
        autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank()
    augroup END
else
    Plug 'machakann/vim-highlightedyank'
endif

call plug#end()

set mouse=a
set scrolloff=5
set number
set relativenumber
set nocursorline
set ttimeoutlen=0
set shiftwidth=4
set tabstop=4
set smartcase
set expandtab
set ignorecase
set hidden
set tags+=.git/tags
set wildmode=list:longest,list:full
set history=50
set complete=.,w,b,u,t
set ruler
set nolist
set showcmd
set incsearch
set nohlsearch
set laststatus=2
set backspace=2
set autowrite
set nowrap
set textwidth=0
set breakindent
set synmaxcol=1024
if has('nvim')
    set termguicolors
endif
set linebreak
" Use global regex replaces by default
set gdefault
" Configure minimum window width
set winwidth=80
set updatetime=250
" If buffer is already open when switching, switch to it
set switchbuf+=useopen
set colorcolumn=100
" configure concealing things
set conceallevel=0

" Center search results
nnoremap <silent> n nzz
nnoremap <silent> N Nzz
nnoremap <silent> * *zz
nnoremap <silent> # #zz
nnoremap <silent> g* g*zz

" Very magic search always
nnoremap / /\v
nnoremap ? ?\v

" Sane splits
set splitright
set splitbelow

if has('nvim')
    set inccommand=nosplit
endif

" --- Set up backups
" Protect changes between writes. Default values of
" updatecount (200 keystrokes) and updatetime
" (4 seconds) are fine
set swapfile
set directory^=~/.vim/swap//

" protect against crash-during-write
set writebackup
" but do not persist backup after successful write
set nobackup
" use rename-and-write-new method whenever safe
set backupcopy=auto
" patch required to honor double slash at end
if has("patch-8.1.0251")
    " consolidate the writebackups -- not a big
    " deal either way, since they usually get deleted
    set backupdir^=~/.vim/backup//
end

" Set up persistent undo
set undofile
set undodir=~/.vimundo

set modeline
set lazyredraw
if !has('nvim')
    set ttyfast
endif

nnoremap <C-h> <C-w><C-h>
nnoremap <C-j> <C-w><C-j>
nnoremap <C-k> <C-w><C-k>
nnoremap <C-l> <C-w><C-l>
nnoremap cp :0,$y+<Cr>
nnoremap ' `
nnoremap ` '
nnoremap j gj
nnoremap k gk

cnoremap %s/ %sm/

" escape with Ctrl-j
inoremap <C-j> <esc>
vnoremap <C-j> <esc>
inoremap <C-c> <esc>
vnoremap <C-c> <esc>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

if executable('rg')
    let &grepprg="rg --vimgrep"
endif

" Configure line breaking
let &showbreak = "> "

" FZF
set rtp+=~/.fzf
let g:fzf_command_prefix = 'Fzf'
nnoremap <leader>f :FzfGitFiles<cr>
nnoremap <leader>F :FzfFiles<cr>
nnoremap gb :FzfBuffers<cr>
nnoremap gl :FzfRg<cr>
nnoremap gL :FzfBLines<cr>
nnoremap <leader>a :FzfAg<cr>

" Configure vim tmux runner
let g:VtrStripLeadingWhitespace = 0
let g:VtrClearEmptyLines = 1
let g:VtrAppendNewline = 1

" Expand %% to the current directory
cnoremap %% <c-r>=expand('%:h') . '/'<cr>

nnoremap <silent> <leader>ve :tabe $MYVIMRC<Cr>
nnoremap <silent> <leader>vr :source $MYVIMRC\|echo "Reloaded!"<Cr>
nnoremap <silent> <leader>ev :echo "Use <leader>ve"<Cr>

" Add mapping to open/close the quickfix list
" Taken from: http://vim.wikia.com/wiki/Toggle_to_open_or_close_the_quickfix_window
function! GetBufferList()
  redir =>buflist
  silent! ls!
  redir END
  return buflist
endfunction

function! ToggleList(bufname, pfx)
  let buflist = GetBufferList()
  for bufnum in map(filter(split(buflist, '\n'), 'v:val =~ "'.a:bufname.'"'), 'str2nr(matchstr(v:val, "\\d\\+"))')
    if bufwinnr(bufnum) != -1
      exec(a:pfx.'close')
      return
    endif
  endfor
  if a:pfx == 'l' && len(getloclist(0)) == 0
      echohl ErrorMsg
      echo "Location List is Empty."
      return
  endif
  let winnr = winnr()
  exec(a:pfx.'open')
  if winnr() != winnr
    wincmd p
  endif
endfunction

" nmap <silent> <leader>l :call ToggleList("Location List", 'l')<CR>
nmap <silent> Q :call ToggleList("Quickfix List", 'c')<CR>

" Bind K to grep word under cursor
nnoremap <silent> K :grep! "<C-R><C-W>"<cr><cr>\|:copen<Cr>

" Default handler to run the current file
function! HandleEnter(cmd)
    if &buftype ==# 'quickfix' || &buftype ==# 'nofile'
        silent execute "normal! \<cr>"
    else
        silent execute "normal! :silent :update" . a:cmd . "\<CR>"
    endif
endfunction

" Default version where only the file is saved
nnoremap <silent> <cr> :call HandleEnter("")<cr>

" Switch panes
nnoremap <leader><leader> <C-^>

" remove help key
map <F1> <Esc>
imap <F1> <Esc>

" Configure vim test
nnoremap <silent> tf :update\|:TestFile<Cr>
nnoremap <silent> tl :update\|:TestLast<Cr>
nnoremap <silent> tn :update\|:TestNearest<Cr>
nnoremap <silent> ta :update\|:TestSuite<Cr>
nnoremap <silent> ts :update\|:TestSuite<Cr>
let test#python#runner = 'pytest'

nnoremap <leader>v :VtrAttachToPane<cr>

" Create shorter 'V' command which is easier to type
command! -nargs=? V call VtrSendCommand(<f-args>)

" Configure vim fugitive
nnoremap <leader>gc :Git commit -v<cr>
nnoremap <leader>gd :Gdiff<cr>
nnoremap <leader>gw :Gwrite<cr>
nnoremap <leader>gr :Gread<cr>
nnoremap gs :Git<cr>
nnoremap <leader>ga :Git commit -v --amend<cr>

" Configure language client
let g:LanguageClient_serverCommands = {
            \ 'rust': ['~/.cargo/bin/rustup', 'run', 'nightly', 'rls'],
            \ 'javascript': ['/usr/local/bin/javascript-typescript-stdio'],
            \ 'javascript.jsx': ['tcp://127.0.0.1:2089'],
            \ 'python': ['/usr/local/bin/pyls'],
            \ }
let g:LanguageClient_autoStart = 1
let g:LanguageClient_useVirtualText = 0
nnoremap <silent> gm :call LanguageClient#textDocument_hover()<CR>

" When editing a file, always jump to the last known cursor position.
" Don't do it for commit messages, when the position is invalid, or when
" inside an event handler (happens when dropping a file on gvim).
autocmd BufReadPost *
\ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
\   exe "normal g`\"" |
\ endif

" Configure neovim's terminal mode
if has('nvim')
    tnoremap <Esc> <C-\><C-n>
    tnoremap <M-[> <Esc>
    tnoremap <C-v><Esc> <Esc>

    autocmd TermOpen * startinsert
endif

" Automatically format elixir files on save
let g:mix_format_on_save = 1

" Configure rust format
let g:rustfmt_autosave = 1
let g:rustfmt_emit_files = 1
let g:rustfmt_fail_silently = 0

if has('nvim')
    runtime! plugin/python_setup.vim
endif

" Disable go version warnings
let g:go_version_warning = 0
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'

" Configure elm.vim
let g:elm_format_fail_silently = 1

" configure conflicted status line
set statusline=%<%f\ %h%m%r%=%-14.(%l,%c%V%)\ %P
set statusline+=%{ConflictedVersion()}

" set up coc status line
set statusline+=\ %{coc#status()}%{get(b:,'coc_current_function','')}

" Enable autoformatting of valid pretter-compatible files
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0

" Start interactive EasyAlign in visual mode (e.g. vip<Enter>)
vmap <Enter> <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

" configure vim notes
let g:notes_directories = ["~/notes"]
function! s:Today()
    let dt = strftime('%Y-%m-%d')
    execute "Note" . dt
endfunction
command! Today call s:Today()

function! s:TODO()
    execute "Note TODO"
endfunction
command! TODO call s:TODO()

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)
nnoremap <silent> gh :CocList symbols<cr>

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

augroup cocgroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType python,rust,json,typescript setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Set up auto formatting
nnoremap <leader>y mm:Format<Cr>`m

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

let g:dispatch_quickfix_height=40
let g:dispatch_tmux_height=40

" configure custom rshtuff test runner
function! RShtuffStrategy(cmd)
    if !exists('g:rshtuff_listener')
        echoerr 'You must define g:rshtuff_listener to use this strategy'
        return
    endif

    call system("rshtuff -n " . shellescape(g:rshtuff_listener) . " send " . shellescape(a:cmd) . " --clear")
endfunction

let g:rshtuff_listener = "testrunner"
let g:test#custom_strategies = {'rshtuff': function('RShtuffStrategy')}
let g:test#strategy = 'basic'

set background=dark
colorscheme srw256
