[package]
name = "wlman"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
color-eyre = "0.6.2"
dbus = "0.9.7"
eyre = "0.6.12"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
shell-words = "1.1.0"
